import os
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import GroupShuffleSplit
import joblib

# Setup paths relative to the `ml/` directory
DATA_DIR = "../data"
TRANSACTIONS_PATH = os.path.join(DATA_DIR, "transactions.csv")
RETRY_ATTEMPTS_PATH = os.path.join(DATA_DIR, "retry_attempts.csv")
MODEL_PATH = "model.pkl"
FEATURES_PATH = "feature_columns.pkl"

def main():
    print("Loading data...")
    # 1. Load CSVs
    try:
        transactions = pd.read_csv(TRANSACTIONS_PATH)
        retries = pd.read_csv(RETRY_ATTEMPTS_PATH)
    except FileNotFoundError as e:
        print(f"Error loading files: {e}")
        print("Ensure you are running the script from the 'ml/' directory and 'data/' exists in the root.")
        return

    # 2. Merge retry_attempts with transactions to bring in features
    # (Assuming both tables have 'transaction_id' and 'customer_id' exists in transactions)
    df = retries.merge(transactions, on="transaction_id", how="inner")
    
    # 3. Engineer feature: is_near_month_boundary
    boundary_days = [1, 2, 3, 28, 29, 30, 31]
    df['is_near_month_boundary'] = df['retry_day_of_month'].isin(boundary_days).astype(int)
    
    # 4 & 5. Define Feature Set & Target
    cat_features = ['failure_reason', 'payment_method', 'issuing_bank', 'transaction_type']
    num_features = ['amount_inr', 'attempt_number', 'hours_since_original_failure', 'retry_day_of_month', 'is_near_month_boundary']
    
    # Encode target (1 for success, 0 for failed)
    df['target'] = (df['retry_outcome'] == 'success').astype(int)
    
    # 6. One-hot encode categorical features
    print("One-hot encoding categorical features...")
    df_encoded = pd.get_dummies(df, columns=cat_features)
    
    # Capture the exact column names generated by get_dummies so we can guarantee 
    # exact feature ordering and presence during inference.
    feature_columns = [col for col in df_encoded.columns if col.startswith(tuple(cat_features))] + num_features
    
    # Ensure all boolean outputs from get_dummies are cast to integers for XGBoost
    for col in feature_columns:
        if df_encoded[col].dtype == bool:
            df_encoded[col] = df_encoded[col].astype(int)
            
    X = df_encoded[feature_columns]
    y = df_encoded['target']
    groups = df_encoded['customer_id']
    
    # --- Split strategy (GroupShuffleSplit) ---
    print("Splitting data by customer_id to prevent data leakage...")
    
    # First split: Separate out 30% for Temp (Validation + Test), leaving 70% for Train
    gss_train = GroupShuffleSplit(n_splits=1, train_size=0.70, random_state=42)
    train_idx, temp_idx = next(gss_train.split(X, y, groups))
    
    X_train, y_train, groups_temp = X.iloc[train_idx], y.iloc[train_idx], groups.iloc[temp_idx]
    X_temp, y_temp = X.iloc[temp_idx], y.iloc[temp_idx]
    
    # Second split: Divide the remaining 30% exactly in half (15% Val, 15% Test)
    gss_val_test = GroupShuffleSplit(n_splits=1, train_size=0.50, random_state=42)
    val_idx, test_idx = next(gss_val_test.split(X_temp, y_temp, groups_temp))
    
    X_val, y_val = X_temp.iloc[val_idx], y_temp.iloc[val_idx]
    X_test, y_test = X_temp.iloc[test_idx], y_temp.iloc[test_idx]
    
    print("-" * 30)
    print("Training progress and split sizes:")
    print(f"  Train size:      {len(X_train):,} rows")
    print(f"  Validation size: {len(X_val):,} rows")
    print(f"  Test size:       {len(X_test):,} rows")
    print("-" * 30)
    
    # --- Model Training ---
    print("Initializing XGBoost classifier...")
    
    # Note: early_stopping_rounds is passed here in newer XGBoost versions
    model = xgb.XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.1,
        eval_metric='logloss',
        early_stopping_rounds=15, 
        random_state=42
    )
    
    print("Training model (with early stopping)...")
    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        verbose=10 # Print metric every 10 trees
    )
    
    # --- Output ---
    print(f"Saving model to {MODEL_PATH}...")
    joblib.dump(model, MODEL_PATH)
    
    print(f"Saving feature structure to {FEATURES_PATH}...")
    joblib.dump(feature_columns, FEATURES_PATH)
    
    print("Training script completed successfully!")

if __name__ == "__main__":
    main()